# Generated by Django 5.2.7 on 2025-12-11 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchaserecord',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='billingaccount',
            name='last_recharged',
        ),
        migrations.RemoveField(
            model_name='billingaccount',
            name='monthly_included',
        ),
        migrations.RemoveField(
            model_name='billingaccount',
            name='payment_provider_customer_id',
        ),
        migrations.AddField(
            model_name='purchaserecord',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='purchaserecord',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='billingaccount',
            name='plan',
            field=models.CharField(choices=[('free', 'Free'), ('pro', 'Pro'), ('team', 'Team')], default='free', max_length=32),
        ),
        migrations.AlterField(
            model_name='purchaserecord',
            name='amount_cents',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchaserecord',
            name='credits',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='purchaserecord',
            name='currency',
            field=models.CharField(default='FCFA', max_length=8),
        ),
        migrations.AlterField(
            model_name='purchaserecord',
            name='pack_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.BigIntegerField()),
                ('type', models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal')], max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='billing.billingaccount')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
