# Generated by Django 5.2.7 on 2025-12-07 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='image',
            field=models.ImageField(blank=True, help_text="Image de couverture de l'enquête (optionnelle).", null=True, upload_to='survey_images/'),
        ),
    ]
