# Generated by Django 5.2.7 on 2025-12-24 18:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0003_respondent_created_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='respondent',
            name='app_version',
        ),
        migrations.RemoveField(
            model_name='respondent',
            name='device_id',
        ),
        migrations.RemoveField(
            model_name='respondent',
            name='synced_at',
        ),
        migrations.RemoveField(
            model_name='respondent',
            name='updated_at_local',
        ),
        migrations.RemoveField(
            model_name='response',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='response',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='respondent',
            name='status',
            field=models.CharField(choices=[('draft', 'Brouillon'), ('pending', 'En attente'), ('synced', 'Synchronisé'), ('error', 'Erreur')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='response',
            name='respondent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='survey.respondent'),
        ),
        migrations.AlterField(
            model_name='response',
            name='selected_choices',
            field=models.ManyToManyField(blank=True, related_name='responses', to='survey.choice'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='survey_images/'),
        ),
    ]
