# Generated by Django 5.2.7 on 2026-02-07 10:30

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0005_alter_survey_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
