# Generated by Django 5.2.7 on 2026-02-07 11:52

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0006_question_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='survey_image'),
        ),
    ]
