# Generated by Django 5.2.7 on 2026-02-10 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0007_alter_survey_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='image',
        ),
    ]
